# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

# The version of the configuration file format.
version: "0.2"
# The locale to use when spell checking. (e.g., en, en-GB, de-DE
language: en
words:
	- TOMA
	- NVMESH
	- SERJIO
	- serjios
	- workqueue
	- netevent
	- mongosh
	- rpmnew
	- clnt
	- dpkg
	- pcpu
	- IOMMU
	- IOMMUs
	- irqbalance
	- excelero
	- journalctl
	- cpulist
	- mlxconfig
	- mstconfig
	- fullspread
	- IRQS
	- APIC
	- nvmeqs
	- arnic
	- persocket
	- taskset
	- goodpath
	- kbytes
	- NVME
	- cmdline
	- mpstat
	- lstopo
	- hwloc
	- ASPM
	- pathing
	- rescan
	- roce
	- nvmeib
	- nvmeibt
	- nvmeiba
	- nvmeibc
	- nvmeibs
	- nvmeshagent
	- nvmeshtracer
	- nvmeshtrace
	- nvmeshcm
	- nvmeshum
	- numactl
	- madvise
	- Broadwell
	- MLNX
	- openib
	- Hugepages
	- BUFS
	- triaging
	- topo
	- rdma
	- dseg
	- bdev
	- dlba
	- gpts
	- SIGUSR
	- killall
	- RDDA
	- nordda
	- nvmeof
	- nvmf
	- rsrc
	- nics
	- gids
	- recov
	- cntr
	- iostats
	- cflags
	- mongorestore
	- johndoe
	- blksets
	- hostnames
	- usec
	- usecs
	- mgmt
	- praid
	- praids
	- tunables
	- nrch
	- ioch
	- instctls
	- volname
	- ioctls
	- enbl
	- IBPI
	- blkst
	- binfo
	- resub
	- Mdeg
	- RVMS
	- fioe
	- nvmeshtarget
	- nvmeshclient
	- nvmeshmgr
	- appsrv
	- targetsrv
	- MYIP
	- truststore
	- numa
	- pernuma
	- fdisk
	- configparser
	- librdkafka
	- softlink
	- destkeystore
	- deststoretype
	- srckeystore
	- srcstoretype
	- deststorepass
	- srcstorepass
	- keytool
	- importkeystore
	- gpgcheck
	- gpgkey
	- blks
	- edic
	- jent
	- libibverbs
	- librdmacm
	- libibcm
	- libibmad
	- libibumad
	- ibverbs
	- OFED
	- Softi
	- iwarp
	- FITRIM
	- iscsi
	- mellanox
	- doca
	- keyrings
	- sourcelist
	- sourceparts
	- storepass
	- kibibytes
	- mebibytes
	- gibibytes
	- tebibytes
	- smartmontools
	- pciutils
	- journaling
	- MOFED
	- cryptsetup
	- crypttab
	- netlink
	- firewalld
	- ABAC
	- insync
	- dport
	- chronyd
	- acks
	- nodesource
	- dearmor
	- inkey
	- noprompt
	- upgrader
	- EWOULDBLOCK
	- sendto
	- Unticketed
	- needrestart
	- nrconf
	- Dapu
	- Exascend
	- Optane
	- Kioxia
	- FIPS
	- Netlist
	- Phison
	- Solidigm
	- Ultrastar
	- EDSFF
	- Bluefield
	- Autofail
	- behaviour
	- BLKDEV
	- charp
	- clocksource
	- cooldown
	- coremask
	- coremasks
	- cpus
	- CPUS
	- datapath
	- dbgdi
	- guids
	- iface
	- iocmd
	- iocmds
	- ioka
	- ipoller
	- IRUGO
	- IWUSR
	- jentry
	- jrange
	- jris
	- jrnl
	- kasan
	- KASAN
	- Keepalive
	- kthread
	- lockset
	- memmgr
	- milli
	- MODPARAM
	- msecs
	- mult
	- nodelay
	- NODELAY
	- noexec
	- norrda
	- percpu
	- prio
	- prpl
	- PRPLs
	- quickack
	- QUICKACK
	- reconf
	- reqs
	- resched
	- SPDK
	- srqs
	- tasklet
	- userspace
	- vecs
	- wakeup
	 - workqueues
	- YNAAH
	- zcopy
	- ullong
	- ecseparationtype
	- HOTPLUG
	- logginglevel
	- notificationlevel
	- onepage
	- raidlevel
	- relogin
	- Relogin
	- upgradeexecutionmodes
	- upgraderedundancylevels
	- vsgs
